// Auto-generated stub — this file was not included in the source bundle
export type Message = any
export const Message: any = null
export type ProgressMessage = any
export const ProgressMessage: any = null
export type AssistantMessage = any
export const AssistantMessage: any = null
export type MessageOrigin = any
export const MessageOrigin: any = null
export type SystemMessage = any
export const SystemMessage: any = null
export type SystemAPIErrorMessage = any
export const SystemAPIErrorMessage: any = null
export type UserMessage = any
export const UserMessage: any = null
export type AttachmentMessage = any
export const AttachmentMessage: any = null
export type RenderableMessage = any
export const RenderableMessage: any = null
export type HookResultMessage = any
export const HookResultMessage: any = null
export type PartialCompactDirection = any
export const PartialCompactDirection: any = null
export type NormalizedUserMessage = any
export const NormalizedUserMessage: any = null
export type SystemMemorySavedMessage = any
export const SystemMemorySavedMessage: any = null
export type SystemStopHookSummaryMessage = any
export const SystemStopHookSummaryMessage: any = null
export type SystemBridgeStatusMessage = any
export const SystemBridgeStatusMessage: any = null
export type SystemTurnDurationMessage = any
export const SystemTurnDurationMessage: any = null
export type SystemThinkingMessage = any
export const SystemThinkingMessage: any = null
export type CollapsedReadSearchGroup = any
export const CollapsedReadSearchGroup: any = null
export type NormalizedAssistantMessage = any
export const NormalizedAssistantMessage: any = null
export type GroupedToolUseMessage = any
export const GroupedToolUseMessage: any = null
export type NormalizedMessage = any
export const NormalizedMessage: any = null
export type SystemInformationalMessage = any
export const SystemInformationalMessage: any = null
